Milestone 3. Game logic.
Luzaks/tic-tac-toe pull request #3
Opened 2019-11-28 22:14 UTC by Luzaks

We build the logic for the tic-tac-toe-game.

2019-11-28 22:54 UTC, stratospherique requested changes
### Great start @Team :clap: :clap: However, I have some suggestion that you need to implement in order to get approval for this milestone. check :arrow_down: 
##### OOP & Project design

* [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] All classes are kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

  - You should think of decoupling the game into concepts that can be translated into classes (objects) able to cummunicate between each other via messages (methods).

- **[REQUIRED]** check code comments below, use the notes to refactor your code :pray: 

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
_**Ahmed Mahfoudh**_

2019-11-28 22:54 UTC, stratospherique commented on lib/logic.rb
> +    end
![image](https://user-images.githubusercontent.com/26124023/69834169-0d12e780-1239-11ea-9212-1b621d7c6ac0.png)
* [ ] No puts/print and get.chomp outside main.rb file.

2019-11-28 22:54 UTC, stratospherique commented on lib/logic.rb
> +  attr_accessor :number, :board, :turn, :array_of_number
* [ ] Use attr_readers/attr_writers instead of attr_accessors.

2019-11-29 18:02 UTC, ebukaume requested changes
## Changes Required!

Hi team :wave: 

Nice of you making some of the changes, but there is more. All your classes should be in the `lib/` directory. Also, see below for more.

**Kindly submit another code review after making the fix**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-29 18:02 UTC, ebukaume commented on lib/logic.rb
> +  attr_writer :number, :turn, :array_of_number, :board
Why would you want to write these attribute from the outside? For example; one can overwrite `turn` without going through `#change_turn`

2019-11-29 18:02 UTC, ebukaume commented on bin/main.rb
> -
Move this class away from `bin/` to `lib/`

2019-11-29 21:54 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi team :wave: 

I see you have removed the `attr_writer`. However, you guys still need to move **all** class away from `bin/` and into `lib/`. 

- [x] Also, please you the [linter configuration](https://github.com/microverseinc/linters-config/tree/master/ruby) provided by Microverse. Please remove all other linter config files.
- [x] Also, fix the permission issue on `bin/main.rb` file.
![review-permission](https://user-images.githubusercontent.com/22497270/69891138-86264380-12fa-11ea-9027-1cf8012fc87b.png)
- [x] Finally, don't forget to remove the `.idea` directory and move the `.gitignore` to the root of the repo.

_I am sorry we didn't mention the last 3 in the previous reviews_

**Kindly submit another code review request after making those changes**. You can also reach me on slack if you need further assistance.

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-02 18:50 UTC, suretrust requested changes
Hi team!

### Amazing job thus far! :raised_hands: I see you have fixed all the other TSE requests.

However, the linter is not properly set up. You don't need to have multiple `.rubocop.yml` or `.rubocop_todo.yml` files. Kindly fix this as appropriate. See [this guide](https://github.com/microverseinc/linters-config/tree/master/ruby) to set it up.

**Please submit for another code review once this has been fixed.** _Happy coding!_ :tada:

2019-12-02 20:59 UTC, ebukaume approved these changes
## Approved! :champagne: 

You gals are really doing great. Please keep the good work up. **You can go ahead and merge this branch.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-02 21:52 UTC, merged